unit LanguageStrings;

interface

uses
	SysUtils,
	Generics.Collections;

{NOTE: Those are vars to support runtime i18n via .lng files.
	InitializeDefaults sets English values at unit load time.
	TranslationRegistry maps key names to var addresses for .lng file parsing.}
var
	ACCOUNT_TRASH: WideString;
	ASK_CONTINUE: WideString;
	ASK_ENCRYPTION_PASSWORD: WideString;
	ASK_OVERWRITE_ACCOUNT: WideString;
	ASK_SAVE_ACCOUNT_CHANGES: WideString;
	ASK_SAVE_STREAMING_CHANGES: WideString;
	ASK_PASSWORD: WideString;
	ASK_PROXY_PASSWORD: WideString;
	CALCULATING_HASH: WideString;
	CALCULATING_HASH_FOR: WideString;
	CANCEL: WideString;
	CHUNK_ABORT: WideString;
	CHUNK_OVERWRITE: WideString;
	CHUNK_SKIP: WideString;
	CHUNK_SKIP_HASH_MATCH: WideString;
	CLONE_FILE_RETRY: WideString;
	CONNECTED_TO: WideString;
	CONTINUE_ASK: WideString;
	CREATE_DIRECTORY: WideString;
	CSRF_UPDATE_REQUIRED: WideString;
	DELETED_ITEM: WideString;
	DELETE_DIR: WideString;
	DELETE_FILE: WideString;
	DESCRIPTION_FROM: WideString;
	DIR_LISTING: WideString;
	DONE: WideString;
	DOWNLOAD_FILE_RETRY: WideString;
	EMPTY: WideString;
	ERR_ACCOUNT_HAS_INVALID_SYMBOL: WideString;
	ERR_ACCOUNT_NAME_INVALID_CHARS: WideString;
	ERR_AUTH_FAILURE: WideString;
	ERR_PASSWORD_CANCELLED: WideString;
	ERR_CLONE_BY_HASH: WideString;
	ERR_CLONE_FILE_ASK: WideString;
	ERR_CLOUD_ERROR_BAD_REQUEST: WideString;
	ERR_CLOUD_ERROR_EXISTS: WideString;
	ERR_CLOUD_ERROR_EXPORT_LIMIT_EXCEEDED: WideString;
	ERR_CLOUD_ERROR_FAHRENHEIT: WideString;
	ERR_CLOUD_ERROR_INVALID: WideString;
	ERR_CLOUD_ERROR_NAME_LENGTH_EXCEEDED: WideString;
	ERR_CLOUD_ERROR_NAME_TOO_LONG: WideString;
	ERR_CLOUD_ERROR_NOT_ACCEPTABLE: WideString;
	ERR_CLOUD_ERROR_NOT_EXISTS: WideString;
	ERR_CLOUD_ERROR_OVERQUOTA: WideString;
	ERR_CLOUD_ERROR_OWN: WideString;
	ERR_CLOUD_ERROR_OWNER: WideString;
	ERR_CLOUD_ERROR_READONLY: WideString;
	ERR_CLOUD_ERROR_REQUIRED: WideString;
	ERR_CLOUD_ERROR_TREES_CONFLICT: WideString;
	ERR_CLOUD_ERROR_UNKNOWN: WideString;
	ERR_CLOUD_ERROR_UNPROCESSABLE_ENTRY: WideString;
	ERR_CLOUD_ERROR_USER_LIMIT_EXCEEDED: WideString;
	ERR_CLOUD_ERROR_VIRUS_SCAN_FAIL: WideString;
	ERR_CONFIRMATION: WideString;
	ERR_COPY_SAME_DIR_NOT_SUPPORTED: WideString;
	ERR_DECRYPT_FAILED: WideString;
	ERR_DELETE: WideString;
	ERR_DELETE_FILE: WideString;
	ERR_DELETE_FILE_ABORT: WideString;
	ERR_DELETE_FILE_ASK: WideString;
	ERR_DELETE_FILE_DELETE: WideString;
	ERR_DELETE_FILE_IGNORE: WideString;
	ERR_DIRECT_COPY_SUPPORT: WideString;
	ERR_DIRECT_OPERATIONS_DISABLED: WideString;
	ERR_DIRECT_OPERATIONS_NOT_SUPPORTED: WideString;
	ERR_DOWNLOAD: WideString;
	ERR_DOWNLOAD_FILE_ASK: WideString;
	ERR_ENCRYPT_FAILED: WideString;
	ERR_FILE_NOT_EXISTS: WideString;
	ERR_FILE_OPEN: WideString;
	ERR_GET_PUBLIC_SHARE: WideString;
	ERR_GET_TEMP_PUBLIC_LINK: WideString;
	ERR_GET_USER_SPACE: WideString;
	ERR_HTTP_GENERAL: WideString;
	ERR_INI_GENERAL: WideString;
	ERR_INSUFFICIENT_STORAGE: WideString;
	ERR_INVALID_IDENTIFIER_NAME: WideString;
	ERR_INVALID_SECTION_NAME: WideString;
	ERR_INVITE_MSG: WideString;
	ERR_JSON_PARSING: WideString;
	ERR_LINE_HASH: WideString;
	ERR_LIST_INVITES_MSG: WideString;
	ERR_LOAD_CAPTCHA: WideString;
	ERR_NAME_TOO_LONG: WideString;
	ERR_NO_MASTER_PASSWORD: WideString;
	ERR_NO_PASSWORDS_STORED: WideString;
	ERR_OPERATION: WideString;
	ERR_OTHER_GENERAL: WideString;
	ERR_PARSING_ANSWER: WideString;
	ERR_PARTIAL_UPLOAD_ABORT: WideString;
	ERR_PARTIAL_UPLOAD_ASK: WideString;
	ERR_PARTIAL_UPLOAD_IGNORE: WideString;
	ERR_PARTIAL_UPLOAD_RETRY: WideString;
	ERR_PARTIAL_UPLOAD_RETRY_EXCEED: WideString;
	ERR_PASSWORD_MATCH: WideString;
	ERR_PUBLISH_FILE: WideString;
	ERR_PUBLISH_FILE_ASK: WideString;
	ERR_PUBLISH_MSG: WideString;
	ERR_READ_BYTES_FROM: WideString;
	ERR_REGISTRATION: WideString;
	ERR_SHARE_FOLDER_MSG: WideString;
	ERR_SOCKET_GENERAL: WideString;
	ERR_TOKEN_UPDATE: WideString;
	ERR_UNPUBLISH_FILE: WideString;
	ERR_UNPUBLISH_MSG: WideString;
	ERR_UNSHARE_FOLDER_MSG: WideString;
	ERR_UPLOAD: WideString;
	ERR_UPLOAD_FILE_ASK: WideString;
	ERR_UPLOAD_INFO: WideString;
	ERR_WHERE_IS_THE_FILE: WideString;
	ERR_WRITE_FAILED: WideString;
	ERR_WRITE_NO_MASTER_PASSWORD: WideString;
	ERR_WRONG_ENCRYPT_PASSWORD: WideString;
	ERR_WRONG_FORMAT: WideString;
	ERR_WRONG_HASH_LENGTH: WideString;
	ERR_WRONG_SIZE_FORMAT: WideString;
	HTTP_REQUEST: WideString;
	HTTP_REQUEST_BODY: WideString;
	HTTP_RESPONSE: WideString;
	HTTP_RESPONSE_BODY: WideString;
	HTTP_REDIRECT: WideString;
	FILE_EXISTS_IGNORE: WideString;
	FILE_EXISTS_OVERWRITE: WideString;
	FILE_FOUND_BY_HASH: WideString;
	INCOMING_LINKS_LISTING: WideString;
	INVITE_FORM_TITLE: WideString;
	LOGIN_IN_PROGRESS: WideString;
	LOGIN_TO: WideString;
	METHOD_STR_HEAD: WideString;
	METHOD_STR_OPTIONS: WideString;
	METHOD_STR_POST: WideString;
	METHOD_STR_RECEIVE: WideString;
	MOUNTED_AS: WideString;
	MULTIPLE_ITEMS: WideString;
	MULTIPLE_ITEMS_DELETED: WideString;
	OK: WideString;
	PARTIAL_UPLOAD_ABORTED: WideString;
	PARTIAL_UPLOAD_INFO: WideString;
	PASSWORD_SAVED: WideString;
	PREFIX_ACCESS_CHANGE: WideString;
	PREFIX_ASK_ENCRYPTION_PASSWORD: WideString;
	PREFIX_ASK_NEW_PASSWORD: WideString;
	PREFIX_ASK_PASSWORD: WideString;
	PREFIX_ASK_PROXY_PASSWORD: WideString;
	PREFIX_ERR_CLOUD_INIT: WideString;
	PREFIX_ERR_DELETE_DIR: WideString;
	PREFIX_ERR_DELETE_FILE: WideString;
	PREFIX_ERR_DIR_LISTING: WideString;
	PREFIX_ERR_FILE_COPY: WideString;
	PREFIX_ERR_FILE_MOVE: WideString;
	PREFIX_ERR_FILE_PUBLISH: WideString;
	PREFIX_ERR_FILE_RENAME: WideString;
	PREFIX_ERR_FILE_RESTORE: WideString;
	PREFIX_ERR_FILE_STATUS: WideString;
	PREFIX_ERR_FILE_UPLOADING: WideString;
	PREFIX_ERR_FOLDER_MOUNT: WideString;
	PREFIX_ERR_FOLDER_UNMOUNT: WideString;
	PREFIX_ERR_GET_USER_SPACE: WideString;
	PREFIX_ERR_INCOMING_REQUESTS_LISTING: WideString;
	PREFIX_ERR_INVITE: WideString;
	PREFIX_ERR_INVITES_LISTING: WideString;
	PREFIX_ERR_INVITE_MEMBER: WideString;
	PREFIX_ERR_INVITE_REJECT: WideString;
	PREFIX_ERR_OAUTH: WideString;
	PREFIX_ERR_PASSWORD_MATCH: WideString;
	PREFIX_ERR_PATH_NOT_EXISTS: WideString;
	PREFIX_ERR_REMOVE_TEMP_PUBLIC_LINK: WideString;
	PREFIX_ERR_SHARD_RECEIVE: WideString;
	PREFIX_ERR_SHARED_LINKS_LISTING: WideString;
	PREFIX_ERR_SHARE_FOLDER: WideString;
	PREFIX_ERR_TRASH_CLEAN: WideString;
	PREFIX_ERR_TRASH_LISTING: WideString;
	PREFIX_ERR_UNSHARE_FOLDER: WideString;
	PREFIX_REDIRECTION_LIMIT: WideString;
	PREFIX_SCAN: WideString;
	PREFIX_SHARD_RECEIVED: WideString;
	PREFIX_STATUS: WideString;
	PROCEED_IGNORE: WideString;
	PROCEED_RETYPE: WideString;
	PROCEED_UPDATE: WideString;
	PUBLISH_FILE_RETRY: WideString;
	REDIRECTION_LIMIT: WideString;
	REQUESTING_OAUTH_TOKEN: WideString;
	SHARD_OVERRIDDEN: WideString;
	SHARED_LINKS_LISTING: WideString;
	SPLIT_LARGE_FILE: WideString;
	SPLIT_LARGE_FILE_IGNORE: WideString;
	SPLIT_PARTIAL_UPLOAD_TITLE: WideString;
	SPLIT_PARTIAL_UPLOAD_MSG: WideString;
	SPLIT_NO_SPACE_MSG: WideString;
	SESSION_EXPIRED: WideString;
	SESSION_REAUTHENTICATED: WideString;
	TOKEN_UPDATED: WideString;
	TRASH_LISTING: WideString;
	TRY_ANOTHER_SHARD: WideString;
	UNDEFINED_DOWNLOAD_SHARD: WideString;
	UNDEFINED_UPLOAD_SHARD: WideString;
	UNKNOWN_ITEM: WideString;
	UNSET_ITEM: WideString;
	UPLOAD_FILE_RETRY: WideString;
	UPLOAD_URL_OVERRIDDEN: WideString;
	URL_OPEN: WideString;
	USER_SPACE_INFO: WideString;
	VERB_SET: WideString;
	VERB_UPDATE: WideString;
	WAIT: WideString;
	WARN_CIPHER_CHANGE: WideString;
	PREFIX_WARN_CIPHER_CHANGE: WideString;
	WARN_ACCOUNT_NAME_SKIPPED: WideString;
	WARN_PROXY_PASSWORD_IGNORED: WideString;
	WARN_QUOTA_EXHAUSTED: WideString;
	WARN_DISPATCHER_UNEXPECTED_FORMAT: WideString;

	{Human-readable translation name displayed in the selection list}
	TRANSLATION_NAME: WideString;

	{DFM visible strings - tab names and button labels}
	DFM_FORM_TITLE: WideString;
	DFM_TAB_ACCOUNTS: WideString;
	DFM_TAB_GLOBAL_SETTINGS: WideString;
	DFM_TAB_NETWORK_SETTINGS: WideString;
	DFM_TAB_FILE_COMMENTS: WideString;
	DFM_TAB_STREAMING: WideString;
	DFM_TAB_TRANSLATION: WideString;
	DFM_BTN_APPLY: WideString;
	DFM_BTN_NEW: WideString;
	DFM_BTN_DELETE: WideString;
	DFM_BTN_SET_PASSWORD: WideString;
	DFM_BTN_RESET_UA: WideString;
	DFM_LBL_ACCOUNT_NAME: WideString;
	DFM_LBL_PUBLIC_URL: WideString;
	DFM_LBL_EMAIL: WideString;
	DFM_LBL_APP_PASSWORD: WideString;
	DFM_LBL_ENCRYPT_FILES: WideString;
	DFM_LBL_ENCRYPT_BACKEND: WideString;
	DFM_LBL_BYTES: WideString;
	DFM_LBL_CHUNK_OVERWRITE: WideString;
	DFM_LBL_DELETE_FAIL_UPLOAD: WideString;
	DFM_LBL_OVERWRITE_LOCAL: WideString;
	DFM_LBL_ICONS_MODE: WideString;
	DFM_LBL_OPERATION_ERROR: WideString;
	DFM_LBL_RETRY_ATTEMPTS: WideString;
	DFM_LBL_RETRY_WAIT: WideString;
	DFM_LBL_MS: WideString;
	DFM_LBL_SHOW_ACCOUNTS: WideString;
	DFM_LBL_COPY_BETWEEN: WideString;
	DFM_LBL_SOCKET_TIMEOUT: WideString;
	DFM_LBL_PROXY_TYPE: WideString;
	DFM_LBL_PROXY_PORT: WideString;
	DFM_LBL_PROXY_USER: WideString;
	DFM_LBL_PROXY_PASSWORD: WideString;
	DFM_LBL_PROXY_SERVER: WideString;
	DFM_LBL_UPLOAD_BPS: WideString;
	DFM_LBL_DOWNLOAD_BPS: WideString;
	DFM_LBL_DESC_FILENAME: WideString;
	DFM_LBL_FILE_EXT: WideString;
	DFM_LBL_COMMAND: WideString;
	DFM_LBL_PARAMETERS: WideString;
	DFM_LBL_START_PATH: WideString;
	DFM_LBL_STREAMING_TYPE: WideString;
	DFM_LBL_LANGUAGE: WideString;
	DFM_COL_ACCOUNT: WideString;
	DFM_COL_TYPE: WideString;
	DFM_COL_EXTENSION: WideString;
	DFM_GB_ACCOUNT_TYPE: WideString;
	DFM_GB_FILE_SIZE: WideString;
	DFM_GB_ENCRYPTION: WideString;
	DFM_GB_PROXY: WideString;
	DFM_GB_SPEED_LIMITS: WideString;
	DFM_RB_PRIVATE: WideString;
	DFM_RB_PUBLIC: WideString;
	DFM_CB_TC_PASSWORD: WideString;
	DFM_CB_UNLIMITED_SIZE: WideString;
	DFM_CB_SPLIT_FILES: WideString;
	DFM_CB_PRESERVE_TIME: WideString;
	DFM_CB_LOAD_SSL: WideString;
	DFM_CB_LOG_SPACE: WideString;
	DFM_CB_OVERRIDE_SPLIT: WideString;
	DFM_CB_DISABLE_MT: WideString;
	DFM_CB_URL_ENCODE: WideString;
	DFM_CB_AUTO_UPDATE: WideString;
	DFM_CB_TRASH: WideString;
	DFM_CB_SHARED: WideString;
	DFM_CB_INVITES: WideString;
	DFM_CB_PRECALC_HASH: WideString;
	DFM_CB_CHECK_CRC: WideString;
	DFM_CB_PROXY_TC_PASSWORD: WideString;
	DFM_CB_CHANGE_UA: WideString;
	DFM_CB_DESC_ENABLED: WideString;
	DFM_CB_DESC_EDITOR: WideString;
	DFM_CB_DESC_COPY_TO: WideString;
	DFM_CB_DESC_COPY_FROM: WideString;
	DFM_CB_DESC_TRACK: WideString;
	{Combobox option strings}
	DFM_OPT_ASK_USER: WideString;
	DFM_OPT_IGNORE_FILE: WideString;
	DFM_OPT_ABORT_OPERATION: WideString;
	DFM_OPT_SILENTLY_OVERWRITE: WideString;
	DFM_OPT_IGNORE: WideString;
	DFM_OPT_RETRY: WideString;
	DFM_OPT_UNSET_RO_IGNORE: WideString;
	DFM_OPT_UNSET_RO_ABORT: WideString;
	DFM_OPT_ENCRYPT_NO: WideString;
	DFM_OPT_ENCRYPT_ALWAYS: WideString;
	DFM_OPT_ENCRYPT_ASK_ONCE: WideString;
	DFM_OPT_ICONS_DEFAULT: WideString;
	DFM_OPT_ICONS_INTERNAL: WideString;
	DFM_OPT_ICONS_INTERNAL_OVERLAY: WideString;
	DFM_OPT_ICONS_EXTERNAL: WideString;
	DFM_OPT_ICONS_EXTERNAL_OVERLAY: WideString;
	DFM_OPT_COPY_DISABLED: WideString;
	DFM_OPT_COPY_VIA_HASH: WideString;
	DFM_OPT_COPY_VIA_LINK: WideString;
	DFM_OPT_HASH_AUTO: WideString;
	DFM_OPT_HASH_DELPHI: WideString;
	DFM_OPT_HASH_BCRYPT: WideString;
	DFM_OPT_HASH_OPENSSL: WideString;
	DFM_OPT_NO_PROXY: WideString;
	DFM_OPT_SOCKS5: WideString;
	DFM_OPT_SOCKS4: WideString;
	DFM_OPT_HTTP: WideString;
	DFM_OPT_STREAM_NONE: WideString;
	DFM_OPT_STREAM_DISABLED: WideString;
	DFM_OPT_STREAM_M3U8: WideString;
	DFM_OPT_STREAM_DEFAULT: WideString;
	DFM_OPT_STREAM_WEB: WideString;
	{Short labels for listview Type columns}
	DFM_LV_ENCRYPT_ALWAYS: WideString;
	DFM_LV_ENCRYPT_ASK: WideString;
	DFM_LV_ENCRYPT_NO: WideString;
	DFM_LV_STREAM_NONE: WideString;
	DFM_LV_STREAM_OFF: WideString;
	DFM_LV_STREAM_M3U8: WideString;
	DFM_LV_STREAM_LINK: WideString;
	DFM_LV_STREAM_WEB: WideString;
	{AskPassword form}
	DFM_ASK_FORM_TITLE: WideString;
	DFM_ASK_LBL_PASSWORD: WideString;
	DFM_ASK_BTN_OK: WideString;
	DFM_ASK_CB_STORE_PWD: WideString;
	{DeletedProperty form}
	DFM_DEL_LBL_NAME: WideString;
	DFM_DEL_LBL_FROM: WideString;
	DFM_DEL_LBL_AT: WideString;
	DFM_DEL_LBL_BY: WideString;
	DFM_DEL_LBL_SIZE: WideString;
	DFM_DEL_BTN_RESTORE: WideString;
	DFM_DEL_BTN_CANCEL: WideString;
	DFM_DEL_BTN_RESTORE_ALL: WideString;
	DFM_DEL_BTN_CLEAR_TRASH: WideString;
	{InviteProperty form}
	DFM_INV_LBL_NAME: WideString;
	DFM_INV_LBL_OWNER_EMAIL: WideString;
	DFM_INV_LBL_OWNER_NAME: WideString;
	DFM_INV_LBL_ACCESS: WideString;
	DFM_INV_LBL_SIZE: WideString;
	DFM_INV_LBL_INVITE_TOKEN: WideString;
	DFM_INV_BTN_MOUNT: WideString;
	DFM_INV_BTN_CANCEL: WideString;
	DFM_INV_BTN_REJECT: WideString;
	DFM_INV_BTN_UNMOUNT_COPY: WideString;
	DFM_INV_BTN_UNMOUNT_DELETE: WideString;
	{RemoteProperty form}
	DFM_REM_LBL_PUBLIC_LINK: WideString;
	DFM_REM_CB_PUBLIC_ACCESS: WideString;
	DFM_REM_BTN_OK: WideString;
	DFM_REM_TAB_FOLDER_ACCESS: WideString;
	DFM_REM_TAB_DOWNLOAD_LINKS: WideString;
	DFM_REM_TAB_HASHES_LIST: WideString;
	DFM_REM_TAB_DESCRIPTION: WideString;
	DFM_REM_LBL_NEW_MEMBER: WideString;
	DFM_REM_LBL_ACCESS: WideString;
	DFM_REM_BTN_ADD: WideString;
	DFM_REM_BTN_SAVE_AS: WideString;
	DFM_REM_BTN_WRAP: WideString;
	DFM_REM_BTN_CANCEL_SCAN: WideString;
	DFM_REM_BTN_RESCAN: WideString;
	DFM_REM_BTN_LOAD_FILE: WideString;
	DFM_REM_BTN_APPLY_HASHES: WideString;
	DFM_REM_BTN_F2_OK: WideString;
	DFM_REM_MI_CHANGE_ACCESS: WideString;
	DFM_REM_MI_DROP_ACCESS: WideString;
	DFM_REM_MI_REFRESH: WideString;
	DFM_REM_OPT_READ_WRITE: WideString;
	DFM_REM_OPT_READ_ONLY: WideString;

	{Translation tab status messages}
	DFM_TRANS_DEFAULT: WideString;
	DFM_TRANS_RESTORED: WideString;
	DFM_TRANS_APPLIED: WideString;
	DFM_TRANS_ERROR: WideString;

	{Content field}
	CONTENT_FIELD_DISABLED: WideString;

	{Translation registry: maps key names to pointers to the corresponding vars}
	TranslationRegistry: TDictionary<string, PWideString>;

procedure InitializeDefaults;
procedure BuildTranslationRegistry;

implementation

procedure InitializeDefaults;
begin
	ACCOUNT_TRASH := '%s trash';
	ASK_CONTINUE := 'Continue operation?';
	ASK_ENCRYPTION_PASSWORD := '%s encryption password';
	ASK_OVERWRITE_ACCOUNT := 'Account "%s" already exists. Overwrite it?';
	ASK_SAVE_ACCOUNT_CHANGES := 'Save changes to account "%s"?';
	ASK_SAVE_STREAMING_CHANGES := 'Save changes to streaming extension "%s"?';
	ASK_PASSWORD := '%s password';
	ASK_PROXY_PASSWORD := 'User %s proxy password';
	CALCULATING_HASH := 'Calculating cloud hash';
	CALCULATING_HASH_FOR := 'Calculating cloud hash for %s';
	CANCEL := 'Cancel';
	CHUNK_ABORT := 'Chunk %s already exists, aborting';
	CHUNK_OVERWRITE := 'Chunk %s already exists, overwriting';
	CHUNK_SKIP := 'Chunk %s already exists, skipping';
	CHUNK_SKIP_HASH_MATCH := 'Chunk %s already exists with matching hash, skipping';
	CLONE_FILE_RETRY := 'File cloning error: %s, retry attempt %d of %d';
	CONNECTED_TO := 'Connected to %s';
	CONTINUE_ASK := 'Continue operation?';
	CREATE_DIRECTORY := 'Create directory';
	CSRF_UPDATE_REQUIRED := 'CSRF token update required during %s %s';
	DELETED_ITEM := 'Deleted item: %s';
	DELETE_DIR := 'Remove directory';
	DELETE_FILE := 'Delete file';
	DESCRIPTION_FROM := 'Description from %s';
	DIR_LISTING := 'Directory listing';
	DONE := 'Done';
	DOWNLOAD_FILE_RETRY := 'Error downloading file %s, retry attempt %d of %d';
	EMPTY := 'Empty';
	ERR_ACCOUNT_HAS_INVALID_SYMBOL := 'File name must contain only valid symbols';
	ERR_ACCOUNT_NAME_INVALID_CHARS := 'Account name cannot contain \, /, [, ] characters or end with .trash, .shared, .invites';
	ERR_AUTH_FAILURE := 'Authorization failed';
	ERR_PASSWORD_CANCELLED := 'Password entry cancelled';
	ERR_CLONE_BY_HASH := 'Error clone by hash: %s, parameter: %s';
	ERR_CLOUD_ERROR_BAD_REQUEST := 'Request to the server failed.';
	ERR_CLOUD_ERROR_EXISTS := 'An object with this name already exists. Please try another name.';
	ERR_CLOUD_ERROR_EXPORT_LIMIT_EXCEEDED := 'Unable to add user. You can create a maximum of 50 shared folders.';
	ERR_CLOUD_ERROR_FAHRENHEIT := 'Unable to create a link. Content publication is blocked upon the demand of the rights holder or an authorized state authority.';
	ERR_CLOUD_ERROR_INVALID := 'Invalid folder name. Folder names cannot contain characters such as "\" * / : < > ? |".';
	ERR_CLOUD_ERROR_NAME_LENGTH_EXCEEDED := 'Folder name length exceeded.';
	ERR_CLOUD_ERROR_NAME_TOO_LONG := 'File name length exceeded.';
	ERR_CLOUD_ERROR_NOT_ACCEPTABLE := 'Cannot add this user.';
	ERR_CLOUD_ERROR_NOT_EXISTS := 'The copied link does not exist.';
	ERR_CLOUD_ERROR_OVERQUOTA := 'Unable to copy; there''s insufficient space in your Cloud.';
	ERR_CLOUD_ERROR_OWN := 'Unable to clone your own link.';
	ERR_CLOUD_ERROR_OWNER := 'Cannot use your own email.';
	ERR_CLOUD_ERROR_READONLY := 'Unable to create. Access is read-only.';
	ERR_CLOUD_ERROR_REQUIRED := 'Folder name cannot be empty.';
	ERR_CLOUD_ERROR_TREES_CONFLICT := 'Cannot make the folder shared if it contains other shared folders or resides in a shared folder.';
	ERR_CLOUD_ERROR_UNKNOWN := 'Unknown error (%d).';
	ERR_CLOUD_ERROR_UNPROCESSABLE_ENTRY := 'Cannot grant access to the file.';
	ERR_CLOUD_ERROR_USER_LIMIT_EXCEEDED := 'Unable to add user. You can have a maximum of 200 users in one shared folder.';
	ERR_CLOUD_ERROR_VIRUS_SCAN_FAIL := 'File is infected with a virus.';
	ERR_CONFIRMATION := 'Confirmation error';
	ERR_COPY_SAME_DIR_NOT_SUPPORTED := 'Copying to the same dir is not supported';
	ERR_DECRYPT_FAILED := 'CryptProc returns an error: Decrypt failed';
	ERR_DELETE := 'Can''t delete %s';
	ERR_DELETE_FILE := 'File deletion error';
	ERR_DELETE_FILE_ABORT := 'Can''t delete file %s, aborted';
	ERR_DELETE_FILE_ASK := 'Can''t delete file %s. Continue operation?';
	ERR_DELETE_FILE_DELETE := 'Read only file %s deleted';
	ERR_DELETE_FILE_IGNORE := 'Can''t delete file %s, ignore';
	ERR_DIRECT_COPY_SUPPORT := 'Direct copying from public accounts is not supported';
	ERR_DIRECT_OPERATIONS_DISABLED := 'Direct operations between accounts are disabled';
	ERR_DIRECT_OPERATIONS_NOT_SUPPORTED := 'Direct operations from public accounts are not supported';
	ERR_DOWNLOAD := 'Download error';
	ERR_ENCRYPT_FAILED := '%s: CryptProc returns an error: Encrypt failed';
	ERR_FILE_NOT_EXISTS := 'File not exists';
	ERR_FILE_OPEN := 'Cannot open file %s: %s';
	ERR_GET_PUBLIC_SHARE := 'Can''t get public share download share';
	ERR_GET_TEMP_PUBLIC_LINK := 'Can''t get temporary public link on %s';
	ERR_GET_USER_SPACE := 'error: getting user space information for %s';
	ERR_HTTP_GENERAL := '%s error with message: %s at %s %s, server response: %s';
	ERR_INI_GENERAL := 'INI file error';
	ERR_INSUFFICIENT_STORAGE := 'Insufficient Storage';
	ERR_INVALID_IDENTIFIER_NAME := 'Invalid identifier name %s';
	ERR_INVALID_SECTION_NAME := 'Invalid section name %s';
	ERR_INVITE_MSG := 'Error while inviting %s to %s folder, see the main log';
	ERR_JSON_PARSING := 'JSON parsing error: %s';
	ERR_LINE_HASH := 'Line %d[%s]: %s';
	ERR_LIST_INVITES_MSG := 'Error while retrieving file %s invites list, see the main log';
	ERR_LOAD_CAPTCHA := 'Can''t load captcha image!';
	ERR_NAME_TOO_LONG := 'Name too long';
	ERR_NO_MASTER_PASSWORD := 'No master password entered yet';
	ERR_NO_PASSWORDS_STORED := 'CryptProc returns an error: No password found in the password store';
	ERR_OPERATION := 'Operation error';
	ERR_OTHER_GENERAL := '%s error with message: %s at %s %s';
	ERR_PARSING_ANSWER := 'Parsing answer';
	ERR_PARTIAL_UPLOAD_ABORT := 'Partial upload error, code: %d, aborted';
	ERR_PARTIAL_UPLOAD_IGNORE := 'Partial upload error, code: %d, ignored';
	ERR_PARTIAL_UPLOAD_RETRY := 'Partial upload error, code: %d, retry attempt %d of %d';
	ERR_PARTIAL_UPLOAD_RETRY_EXCEED := 'Partial upload error, code: %d, retry attempt limit exceed, aborted';
	ERR_PASSWORD_MATCH := 'The specified password does not match the previously entered one. If you choose to use the new password, previously encrypted files become inaccessible.';
	ERR_PUBLISH_FILE := 'File publishing error';
	ERR_PUBLISH_MSG := 'Error while publishing file %s, see the main log';
	ERR_READ_BYTES_FROM := 'Can''t read from %s %d bytes at %d';
	ERR_REGISTRATION := 'Registration error';
	ERR_SHARE_FOLDER_MSG := 'Error while share access to %s from %s folder, see the main log';
	ERR_SOCKET_GENERAL := '%s network error: %s at %s %s';
	ERR_TOKEN_UPDATE := 'Token update error!';
	ERR_UNPUBLISH_FILE := 'File unpublishing error';
	ERR_UNPUBLISH_MSG := 'Error while unpublishing file %s, see the main log';
	ERR_UNSHARE_FOLDER_MSG := 'Error while remove access to %s to %s folder, see the main log';
	ERR_UPLOAD := 'Upload error';
	ERR_UPLOAD_INFO := 'error: uploading to cloud: %s with message: %s';
	ERR_WHERE_IS_THE_FILE := 'Can''t find the file %s';
	ERR_WRITE_FAILED := '%s: password is not saved: Can''t write the password to the password store';
	ERR_WRONG_ENCRYPT_PASSWORD := 'Incorrect encryption password, encryption support disabled';
	ERR_WRONG_FORMAT := 'Parameter should be in hash:size:name or hash:size format.';
	ERR_WRONG_HASH_LENGTH := 'Hash length should be exactly 40 symbols.';
	ERR_WRONG_SIZE_FORMAT := 'Size should be in numeric format.';
	HTTP_REQUEST := '>> %s %s';
	HTTP_REQUEST_BODY := '>> %s %s [%d bytes]';
	HTTP_RESPONSE := '<< %s %d [%d bytes]';
	HTTP_RESPONSE_BODY := '<< %s';
	HTTP_REDIRECT := '<< %s -> %s';
	FILE_EXISTS_IGNORE := 'Local file %s exists, ignored';
	FILE_EXISTS_OVERWRITE := 'Local file %s exists, and will be overwritten';
	FILE_FOUND_BY_HASH := 'File "%s" found by hash';
	INCOMING_LINKS_LISTING := 'Incoming links listing';
	INVITE_FORM_TITLE := '%s invite: %s';
	LOGIN_IN_PROGRESS := 'Login to account...';
	LOGIN_TO := 'Login to %s';
	METHOD_STR_HEAD := 'check';
	METHOD_STR_OPTIONS := 'request parameters from';
	METHOD_STR_POST := 'post data to';
	METHOD_STR_RECEIVE := 'receive data from';
	MOUNTED_AS := 'Mounted as:';
	MULTIPLE_ITEMS := '<Multiple items>';
	MULTIPLE_ITEMS_DELETED := 'Multiple deleted items';
	OK := 'Ok';
	PARTIAL_UPLOAD_ABORTED := 'Partial upload aborted';
	PARTIAL_UPLOAD_INFO := 'Partial upload of %s part %d of %d => %s';
	PASSWORD_SAVED := '%s: the password saved in the TC password manager';
	PREFIX_ACCESS_CHANGE := 'Change access to %s';
	PREFIX_ASK_ENCRYPTION_PASSWORD := 'Enter encryption password for current session:';
	PREFIX_ASK_NEW_PASSWORD := 'New password:';
	PREFIX_ASK_PASSWORD := 'Enter account password:';
	PREFIX_ASK_PROXY_PASSWORD := 'Enter proxy password:';
	PREFIX_ERR_CLOUD_INIT := 'Cloud initialization error: ';
	PREFIX_ERR_DELETE_DIR := 'Directory deletion error: ';
	PREFIX_ERR_DELETE_FILE := 'Delete file error: ';
	PREFIX_ERR_DIR_LISTING := 'Directory listing error: ';
	PREFIX_ERR_FILE_COPY := 'File copy error: ';
	PREFIX_ERR_FILE_MOVE := 'File move error: ';
	PREFIX_ERR_FILE_PUBLISH := 'File publish error: ';
	PREFIX_ERR_FILE_RENAME := 'File renaming error: ';
	PREFIX_ERR_FILE_RESTORE := 'File restore error: ';
	PREFIX_ERR_FILE_STATUS := 'File status error: ';
	PREFIX_ERR_FILE_UPLOADING := 'File uploading error: ';
	PREFIX_ERR_FOLDER_MOUNT := 'Folder mount error: ';
	PREFIX_ERR_FOLDER_UNMOUNT := 'Folder unmount error: ';
	PREFIX_ERR_GET_USER_SPACE := 'User space receiving error: ';
	PREFIX_ERR_INCOMING_REQUESTS_LISTING := 'Incoming requests listing error: ';
	PREFIX_ERR_INVITE := 'Folder invite error';
	PREFIX_ERR_INVITES_LISTING := 'Invite listing error';
	PREFIX_ERR_INVITE_MEMBER := 'Invite member error: ';
	PREFIX_ERR_INVITE_REJECT := 'Invite rejection error: ';
	PREFIX_ERR_OAUTH := 'OAuth error: %s (%s).';
	PREFIX_ERR_PASSWORD_MATCH := 'Password doesn''t match!';
	PREFIX_ERR_PATH_NOT_EXISTS := 'Path not exists: ';
	PREFIX_ERR_REMOVE_TEMP_PUBLIC_LINK := 'Can''t remove temporary public link on ';
	PREFIX_ERR_SHARD_RECEIVE := 'Shard receive error: ';
	PREFIX_ERR_SHARED_LINKS_LISTING := 'Shared links listing error: ';
	PREFIX_ERR_SHARE_FOLDER := 'Folder share error';
	PREFIX_ERR_TRASH_CLEAN := 'Trash bin clear error: ';
	PREFIX_ERR_TRASH_LISTING := 'Trash bin listing error: ';
	PREFIX_ERR_UNSHARE_FOLDER := 'Folder unshare error';
	PREFIX_REDIRECTION_LIMIT := 'Redirection limit reached when trying to download ';
	PREFIX_SCAN := 'Scanning %s';
	PREFIX_SHARD_RECEIVED := 'Shard received: %s, type: %s';
	PREFIX_STATUS := 'Status: ';
	PROCEED_IGNORE := 'Proceed without encryption';
	PROCEED_RETYPE := 'Retype password';
	PROCEED_UPDATE := 'Use the new password';
	PUBLISH_FILE_RETRY := 'File publish error: %s, retry attempt %d of %d';
	REDIRECTION_LIMIT := 'Redirection limit';
	REQUESTING_OAUTH_TOKEN := 'Requesting OAuth token for %s';
	SHARD_OVERRIDDEN := 'Shard is overridden via config!';
	SHARED_LINKS_LISTING := 'Shared links listing';
	SPLIT_LARGE_FILE := 'File size > %d bytes, file will be split';
	SPLIT_LARGE_FILE_IGNORE := 'File size > %d bytes, ignored';
	SPLIT_PARTIAL_UPLOAD_TITLE := 'Insufficient cloud storage';
	SPLIT_PARTIAL_UPLOAD_MSG := 'Not enough space for the entire file.'#13#10'Available: %s, File size: %s'#13#10#13#10'Only %d of %d chunks can be uploaded.'#13#10'Continue with partial upload?';
	SPLIT_NO_SPACE_MSG := 'Not enough space to upload.'#13#10'Available: %s, Required: %s';
	SESSION_EXPIRED := 'OAuth session expired, attempting re-authentication';
	SESSION_REAUTHENTICATED := 'Successfully re-authenticated after session expiry';
	TOKEN_UPDATED := 'Token updated';
	TRASH_LISTING := 'Trash bin listing';
	TRY_ANOTHER_SHARD := 'Try with another shard?';
	UNDEFINED_DOWNLOAD_SHARD := 'Current download shard is undefined, trying to get one';
	UNDEFINED_UPLOAD_SHARD := 'Current upload shard is undefined, trying to get one';
	UNKNOWN_ITEM := '...';
	UNSET_ITEM := '-';
	UPLOAD_FILE_RETRY := 'Error uploading file %s, retry attempt %d of %d';
	UPLOAD_URL_OVERRIDDEN := 'Upload url is overridden via config!';
	URL_OPEN := 'Open %s';
	USER_SPACE_INFO := 'Total space: %s, used: %s, free: %s.%s';
	VERB_SET := 'Set';
	VERB_UPDATE := 'Update';
	WAIT := 'Wait for it...';
	WARN_CIPHER_CHANGE := 'Changing the encryption profile will make previously encrypted files unreadable with the new profile. Only newly encrypted files will use the selected profile. Continue?';
	PREFIX_WARN_CIPHER_CHANGE := 'Cipher profile change';
	WARN_ACCOUNT_NAME_SKIPPED := 'Account "%s" skipped: name contains invalid characters (\, /, [, ]) or ends with a reserved suffix';
	WARN_PROXY_PASSWORD_IGNORED := 'Warning: proxy password input skipped ignored, parameter will be ignored!';
	WARN_QUOTA_EXHAUSTED := 'Warning: space quota exhausted!';
	WARN_DISPATCHER_UNEXPECTED_FORMAT := 'OAuth dispatcher returned unexpected response format: %s';

	{Compound strings - must be set AFTER their dependencies}
	ERR_CLONE_FILE_ASK := 'File cloning error: %s' + SLineBreak + CONTINUE_ASK;
	ERR_DOWNLOAD_FILE_ASK := 'Error downloading file' + SLineBreak + '%s' + SLineBreak + CONTINUE_ASK;
	ERR_PARTIAL_UPLOAD_ASK := 'Partial upload error, code: %d' + SLineBreak + 'part name: %s' + SLineBreak + ASK_CONTINUE;
	ERR_PUBLISH_FILE_ASK := 'File publish error: %s' + SLineBreak + CONTINUE_ASK;
	ERR_UPLOAD_FILE_ASK := 'Error uploading file' + SLineBreak + '%s' + SLineBreak + CONTINUE_ASK;
	ERR_WRITE_NO_MASTER_PASSWORD := '%s: password is not saved: ' + ERR_NO_MASTER_PASSWORD;

	TRANSLATION_NAME := '';

	{DFM visible strings}
	DFM_FORM_TITLE := 'Cloud Accounts';
	DFM_TAB_ACCOUNTS := 'Accounts';
	DFM_TAB_GLOBAL_SETTINGS := 'Global settings';
	DFM_TAB_NETWORK_SETTINGS := 'Network settings';
	DFM_TAB_FILE_COMMENTS := 'File comments support';
	DFM_TAB_STREAMING := 'Streaming settings';
	DFM_TAB_TRANSLATION := 'Translation';
	DFM_BTN_APPLY := 'Apply';
	DFM_BTN_NEW := 'New';
	DFM_BTN_DELETE := 'Delete';
	DFM_BTN_SET_PASSWORD := 'Set password';
	DFM_BTN_RESET_UA := 'Reset';
	DFM_LBL_ACCOUNT_NAME := 'Account name';
	DFM_LBL_PUBLIC_URL := 'Public url:';
	DFM_LBL_EMAIL := 'Email:';
	DFM_LBL_APP_PASSWORD := 'App password (create at id.mail.ru):';
	DFM_LBL_ENCRYPT_FILES := 'Encrypt/decrypt files';
	DFM_LBL_ENCRYPT_BACKEND := 'Encryption backend';
	DFM_LBL_BYTES := 'bytes';
	DFM_LBL_CHUNK_OVERWRITE := 'Overwrite splitted chunk mode:';
	DFM_LBL_DELETE_FAIL_UPLOAD := 'Delete file after upload mode:';
	DFM_LBL_OVERWRITE_LOCAL := 'Overwrite local files mode:';
	DFM_LBL_ICONS_MODE := 'Plugin icons mode:';
	DFM_LBL_OPERATION_ERROR := 'On downloads/uploads error:';
	DFM_LBL_RETRY_ATTEMPTS := 'Retry attempts:';
	DFM_LBL_RETRY_WAIT := 'wait';
	DFM_LBL_MS := 'ms';
	DFM_LBL_SHOW_ACCOUNTS := 'Show accounts:';
	DFM_LBL_COPY_BETWEEN := 'Copying/moving between accounts:';
	DFM_LBL_SOCKET_TIMEOUT := 'Network operations timeout, ms (0 = unlimited):';
	DFM_LBL_PROXY_TYPE := 'Proxy type';
	DFM_LBL_PROXY_PORT := 'Port';
	DFM_LBL_PROXY_USER := 'Proxy authentication username (blank for none)';
	DFM_LBL_PROXY_PASSWORD := 'Proxy authentication password';
	DFM_LBL_PROXY_SERVER := 'Proxy server';
	DFM_LBL_UPLOAD_BPS := 'Limit uploads bits per second (0 for none):';
	DFM_LBL_DOWNLOAD_BPS := 'Limit downloads bits per second (0 for none):';
	DFM_LBL_DESC_FILENAME := 'Override descript.ion file name:';
	DFM_LBL_FILE_EXT := 'File extension';
	DFM_LBL_COMMAND := 'Command';
	DFM_LBL_PARAMETERS := 'Parameters (%url% for stream url substitution)';
	DFM_LBL_START_PATH := 'Start path';
	DFM_LBL_STREAMING_TYPE := 'Streaming type';
	DFM_LBL_LANGUAGE := 'Language';
	DFM_COL_ACCOUNT := 'Account';
	DFM_COL_TYPE := 'Type';
	DFM_COL_EXTENSION := 'Extension';
	DFM_GB_ACCOUNT_TYPE := 'Account type';
	DFM_GB_FILE_SIZE := 'File size';
	DFM_GB_ENCRYPTION := 'Encryption';
	DFM_GB_PROXY := 'Proxy settings';
	DFM_GB_SPEED_LIMITS := 'Speed limits';
	DFM_RB_PRIVATE := 'Private';
	DFM_RB_PUBLIC := 'Public';
	DFM_CB_TC_PASSWORD := 'Store password in TC password manager';
	DFM_CB_UNLIMITED_SIZE := 'Ignore 2Gb limit (paid account)';
	DFM_CB_SPLIT_FILES := 'Split large files';
	DFM_CB_PRESERVE_TIME := 'Preserve file creation time';
	DFM_CB_LOAD_SSL := 'Load SSL libraries only from plugin directory';
	DFM_CB_LOG_SPACE := 'Enable space info logging';
	DFM_CB_OVERRIDE_SPLIT := 'Override split file size to';
	DFM_CB_DISABLE_MT := 'Disable background operations support';
	DFM_CB_URL_ENCODE := 'URL encode direct download links';
	DFM_CB_AUTO_UPDATE := 'Update direct download links immediately';
	DFM_CB_TRASH := 'Trash folders';
	DFM_CB_SHARED := 'Shared links folders';
	DFM_CB_INVITES := 'Invites folders';
	DFM_CB_PRECALC_HASH := 'Try to find files by hash before uploading';
	DFM_CB_CHECK_CRC := 'Check uploads/downloads CRC';
	DFM_CB_PROXY_TC_PASSWORD := 'Store proxy password in TC password manager';
	DFM_CB_CHANGE_UA := 'Change plugin UserAgent';
	DFM_CB_DESC_ENABLED := 'Read descript.ion comments from cloud filesystem';
	DFM_CB_DESC_EDITOR := 'Enable descript.ion editor';
	DFM_CB_DESC_COPY_TO := 'Copy descript.ion comments to cloud';
	DFM_CB_DESC_COPY_FROM := 'Copy descript.ion comments from cloud';
	DFM_CB_DESC_TRACK := 'Track cloud filesystem changes';
	{Combobox option strings}
	DFM_OPT_ASK_USER := 'Ask user';
	DFM_OPT_IGNORE_FILE := 'Ignore file';
	DFM_OPT_ABORT_OPERATION := 'Abort operation';
	DFM_OPT_SILENTLY_OVERWRITE := 'Silently overwrite';
	DFM_OPT_IGNORE := 'Ignore';
	DFM_OPT_RETRY := 'Retry with this file';
	DFM_OPT_UNSET_RO_IGNORE := 'Try to unset read only flag and delete, ignore file on error';
	DFM_OPT_UNSET_RO_ABORT := 'Try to unset read only flag and delete, abort operation on error';
	DFM_OPT_ENCRYPT_NO := 'No';
	DFM_OPT_ENCRYPT_ALWAYS := 'Always';
	DFM_OPT_ENCRYPT_ASK_ONCE := 'Ask once';
	DFM_OPT_ICONS_DEFAULT := 'System default';
	DFM_OPT_ICONS_INTERNAL := 'Internal icons';
	DFM_OPT_ICONS_INTERNAL_OVERLAY := 'Internal icons overlay';
	DFM_OPT_ICONS_EXTERNAL := 'External icons';
	DFM_OPT_ICONS_EXTERNAL_OVERLAY := 'External icons overlay';
	DFM_OPT_COPY_DISABLED := 'Disabled';
	DFM_OPT_COPY_VIA_HASH := 'Via hash (recommended)';
	DFM_OPT_COPY_VIA_LINK := 'Via public link';
	DFM_OPT_HASH_AUTO := 'Autoselect (BCrypt > OpenSSL > Delphi)';
	DFM_OPT_HASH_DELPHI := 'Delphi implementation';
	DFM_OPT_HASH_BCRYPT := 'BCrypt (Windows BCrypt/CNG API)';
	DFM_OPT_HASH_OPENSSL := 'OpenSSL (OpenSSL EVP)';
	DFM_OPT_NO_PROXY := 'No proxy';
	DFM_OPT_SOCKS5 := 'Socks5';
	DFM_OPT_SOCKS4 := 'Socks4';
	DFM_OPT_HTTP := 'HTTP(S)';
	DFM_OPT_STREAM_NONE := 'None (download and open file)';
	DFM_OPT_STREAM_DISABLED := 'Disabled (no action)';
	DFM_OPT_STREAM_M3U8 := 'M3U8 playlist (useful for media files)';
	DFM_OPT_STREAM_DEFAULT := 'Default (publish file & get download link)';
	DFM_OPT_STREAM_WEB := 'Weblink (publish file & get web link)';
	{Short labels for listview Type columns}
	DFM_LV_ENCRYPT_ALWAYS := 'Alw';
	DFM_LV_ENCRYPT_ASK := 'Ask';
	DFM_LV_ENCRYPT_NO := 'No';
	DFM_LV_STREAM_NONE := 'None';
	DFM_LV_STREAM_OFF := 'Off';
	DFM_LV_STREAM_M3U8 := 'M3U8';
	DFM_LV_STREAM_LINK := 'Link';
	DFM_LV_STREAM_WEB := 'Web';
	{AskPassword form}
	DFM_ASK_FORM_TITLE := 'Password';
	DFM_ASK_LBL_PASSWORD := 'Enter account password:';
	DFM_ASK_BTN_OK := 'OK';
	DFM_ASK_CB_STORE_PWD := 'Store password in TC password manager';
	{DeletedProperty form}
	DFM_DEL_LBL_NAME := 'Name:';
	DFM_DEL_LBL_FROM := 'Deleted from:';
	DFM_DEL_LBL_AT := 'Deleted at:';
	DFM_DEL_LBL_BY := 'Deleted by';
	DFM_DEL_LBL_SIZE := 'Summary size:';
	DFM_DEL_BTN_RESTORE := 'Restore';
	DFM_DEL_BTN_CANCEL := 'Cancel';
	DFM_DEL_BTN_RESTORE_ALL := 'Restore all';
	DFM_DEL_BTN_CLEAR_TRASH := 'Clear trash';
	{InviteProperty form}
	DFM_INV_LBL_NAME := 'Name:';
	DFM_INV_LBL_OWNER_EMAIL := 'Owner email:';
	DFM_INV_LBL_OWNER_NAME := 'Owner name:';
	DFM_INV_LBL_ACCESS := 'Access:';
	DFM_INV_LBL_SIZE := 'Summary size:';
	DFM_INV_LBL_INVITE_TOKEN := 'Invite token:';
	DFM_INV_BTN_MOUNT := 'Mount';
	DFM_INV_BTN_CANCEL := 'Cancel';
	DFM_INV_BTN_REJECT := 'Reject';
	DFM_INV_BTN_UNMOUNT_COPY := 'Unmount (save copy)';
	DFM_INV_BTN_UNMOUNT_DELETE := 'Unmount and delete';
	{RemoteProperty form}
	DFM_REM_LBL_PUBLIC_LINK := 'Public link:';
	DFM_REM_CB_PUBLIC_ACCESS := 'Public access enabled';
	DFM_REM_BTN_OK := 'OK';
	DFM_REM_TAB_FOLDER_ACCESS := 'Folder access';
	DFM_REM_TAB_DOWNLOAD_LINKS := 'Download links';
	DFM_REM_TAB_HASHES_LIST := 'Hashes list';
	DFM_REM_TAB_DESCRIPTION := 'Description';
	DFM_REM_LBL_NEW_MEMBER := 'New member email:';
	DFM_REM_LBL_ACCESS := 'Access:';
	DFM_REM_BTN_ADD := 'Add';
	DFM_REM_BTN_SAVE_AS := 'Save as';
	DFM_REM_BTN_WRAP := 'Wrap';
	DFM_REM_BTN_CANCEL_SCAN := 'Cancel scan';
	DFM_REM_BTN_RESCAN := 'Rescan';
	DFM_REM_BTN_LOAD_FILE := 'Load from file';
	DFM_REM_BTN_APPLY_HASHES := 'Apply hashes';
	DFM_REM_BTN_F2_OK := 'F2 OK';
	DFM_REM_MI_CHANGE_ACCESS := 'Change access';
	DFM_REM_MI_DROP_ACCESS := 'Drop access';
	DFM_REM_MI_REFRESH := 'Refresh';
	DFM_REM_OPT_READ_WRITE := 'Read and write';
	DFM_REM_OPT_READ_ONLY := 'Read only';

	DFM_TRANS_DEFAULT := '(Default)';
	DFM_TRANS_RESTORED := 'Defaults restored';
	DFM_TRANS_APPLIED := 'Translation applied: %s';
	DFM_TRANS_ERROR := 'Error: %s';

	CONTENT_FIELD_DISABLED := '<disabled>';
end;

procedure BuildTranslationRegistry;
begin
	if TranslationRegistry <> nil then
		TranslationRegistry.Free;
	TranslationRegistry := TDictionary<string, PWideString>.Create;

	TranslationRegistry.Add('ACCOUNT_TRASH', @ACCOUNT_TRASH);
	TranslationRegistry.Add('ASK_CONTINUE', @ASK_CONTINUE);
	TranslationRegistry.Add('ASK_ENCRYPTION_PASSWORD', @ASK_ENCRYPTION_PASSWORD);
	TranslationRegistry.Add('ASK_OVERWRITE_ACCOUNT', @ASK_OVERWRITE_ACCOUNT);
	TranslationRegistry.Add('ASK_SAVE_ACCOUNT_CHANGES', @ASK_SAVE_ACCOUNT_CHANGES);
	TranslationRegistry.Add('ASK_SAVE_STREAMING_CHANGES', @ASK_SAVE_STREAMING_CHANGES);
	TranslationRegistry.Add('ASK_PASSWORD', @ASK_PASSWORD);
	TranslationRegistry.Add('ASK_PROXY_PASSWORD', @ASK_PROXY_PASSWORD);
	TranslationRegistry.Add('CALCULATING_HASH', @CALCULATING_HASH);
	TranslationRegistry.Add('CALCULATING_HASH_FOR', @CALCULATING_HASH_FOR);
	TranslationRegistry.Add('CANCEL', @CANCEL);
	TranslationRegistry.Add('CHUNK_ABORT', @CHUNK_ABORT);
	TranslationRegistry.Add('CHUNK_OVERWRITE', @CHUNK_OVERWRITE);
	TranslationRegistry.Add('CHUNK_SKIP', @CHUNK_SKIP);
	TranslationRegistry.Add('CHUNK_SKIP_HASH_MATCH', @CHUNK_SKIP_HASH_MATCH);
	TranslationRegistry.Add('CLONE_FILE_RETRY', @CLONE_FILE_RETRY);
	TranslationRegistry.Add('CONNECTED_TO', @CONNECTED_TO);
	TranslationRegistry.Add('CONTINUE_ASK', @CONTINUE_ASK);
	TranslationRegistry.Add('CREATE_DIRECTORY', @CREATE_DIRECTORY);
	TranslationRegistry.Add('CSRF_UPDATE_REQUIRED', @CSRF_UPDATE_REQUIRED);
	TranslationRegistry.Add('DELETED_ITEM', @DELETED_ITEM);
	TranslationRegistry.Add('DELETE_DIR', @DELETE_DIR);
	TranslationRegistry.Add('DELETE_FILE', @DELETE_FILE);
	TranslationRegistry.Add('DESCRIPTION_FROM', @DESCRIPTION_FROM);
	TranslationRegistry.Add('DIR_LISTING', @DIR_LISTING);
	TranslationRegistry.Add('DONE', @DONE);
	TranslationRegistry.Add('DOWNLOAD_FILE_RETRY', @DOWNLOAD_FILE_RETRY);
	TranslationRegistry.Add('EMPTY', @EMPTY);
	TranslationRegistry.Add('ERR_ACCOUNT_HAS_INVALID_SYMBOL', @ERR_ACCOUNT_HAS_INVALID_SYMBOL);
	TranslationRegistry.Add('ERR_ACCOUNT_NAME_INVALID_CHARS', @ERR_ACCOUNT_NAME_INVALID_CHARS);
	TranslationRegistry.Add('ERR_AUTH_FAILURE', @ERR_AUTH_FAILURE);
	TranslationRegistry.Add('ERR_PASSWORD_CANCELLED', @ERR_PASSWORD_CANCELLED);
	TranslationRegistry.Add('ERR_CLONE_BY_HASH', @ERR_CLONE_BY_HASH);
	TranslationRegistry.Add('ERR_CLONE_FILE_ASK', @ERR_CLONE_FILE_ASK);
	TranslationRegistry.Add('ERR_CLOUD_ERROR_BAD_REQUEST', @ERR_CLOUD_ERROR_BAD_REQUEST);
	TranslationRegistry.Add('ERR_CLOUD_ERROR_EXISTS', @ERR_CLOUD_ERROR_EXISTS);
	TranslationRegistry.Add('ERR_CLOUD_ERROR_EXPORT_LIMIT_EXCEEDED', @ERR_CLOUD_ERROR_EXPORT_LIMIT_EXCEEDED);
	TranslationRegistry.Add('ERR_CLOUD_ERROR_FAHRENHEIT', @ERR_CLOUD_ERROR_FAHRENHEIT);
	TranslationRegistry.Add('ERR_CLOUD_ERROR_INVALID', @ERR_CLOUD_ERROR_INVALID);
	TranslationRegistry.Add('ERR_CLOUD_ERROR_NAME_LENGTH_EXCEEDED', @ERR_CLOUD_ERROR_NAME_LENGTH_EXCEEDED);
	TranslationRegistry.Add('ERR_CLOUD_ERROR_NAME_TOO_LONG', @ERR_CLOUD_ERROR_NAME_TOO_LONG);
	TranslationRegistry.Add('ERR_CLOUD_ERROR_NOT_ACCEPTABLE', @ERR_CLOUD_ERROR_NOT_ACCEPTABLE);
	TranslationRegistry.Add('ERR_CLOUD_ERROR_NOT_EXISTS', @ERR_CLOUD_ERROR_NOT_EXISTS);
	TranslationRegistry.Add('ERR_CLOUD_ERROR_OVERQUOTA', @ERR_CLOUD_ERROR_OVERQUOTA);
	TranslationRegistry.Add('ERR_CLOUD_ERROR_OWN', @ERR_CLOUD_ERROR_OWN);
	TranslationRegistry.Add('ERR_CLOUD_ERROR_OWNER', @ERR_CLOUD_ERROR_OWNER);
	TranslationRegistry.Add('ERR_CLOUD_ERROR_READONLY', @ERR_CLOUD_ERROR_READONLY);
	TranslationRegistry.Add('ERR_CLOUD_ERROR_REQUIRED', @ERR_CLOUD_ERROR_REQUIRED);
	TranslationRegistry.Add('ERR_CLOUD_ERROR_TREES_CONFLICT', @ERR_CLOUD_ERROR_TREES_CONFLICT);
	TranslationRegistry.Add('ERR_CLOUD_ERROR_UNKNOWN', @ERR_CLOUD_ERROR_UNKNOWN);
	TranslationRegistry.Add('ERR_CLOUD_ERROR_UNPROCESSABLE_ENTRY', @ERR_CLOUD_ERROR_UNPROCESSABLE_ENTRY);
	TranslationRegistry.Add('ERR_CLOUD_ERROR_USER_LIMIT_EXCEEDED', @ERR_CLOUD_ERROR_USER_LIMIT_EXCEEDED);
	TranslationRegistry.Add('ERR_CLOUD_ERROR_VIRUS_SCAN_FAIL', @ERR_CLOUD_ERROR_VIRUS_SCAN_FAIL);
	TranslationRegistry.Add('ERR_CONFIRMATION', @ERR_CONFIRMATION);
	TranslationRegistry.Add('ERR_COPY_SAME_DIR_NOT_SUPPORTED', @ERR_COPY_SAME_DIR_NOT_SUPPORTED);
	TranslationRegistry.Add('ERR_DECRYPT_FAILED', @ERR_DECRYPT_FAILED);
	TranslationRegistry.Add('ERR_DELETE', @ERR_DELETE);
	TranslationRegistry.Add('ERR_DELETE_FILE', @ERR_DELETE_FILE);
	TranslationRegistry.Add('ERR_DELETE_FILE_ABORT', @ERR_DELETE_FILE_ABORT);
	TranslationRegistry.Add('ERR_DELETE_FILE_ASK', @ERR_DELETE_FILE_ASK);
	TranslationRegistry.Add('ERR_DELETE_FILE_DELETE', @ERR_DELETE_FILE_DELETE);
	TranslationRegistry.Add('ERR_DELETE_FILE_IGNORE', @ERR_DELETE_FILE_IGNORE);
	TranslationRegistry.Add('ERR_DIRECT_COPY_SUPPORT', @ERR_DIRECT_COPY_SUPPORT);
	TranslationRegistry.Add('ERR_DIRECT_OPERATIONS_DISABLED', @ERR_DIRECT_OPERATIONS_DISABLED);
	TranslationRegistry.Add('ERR_DIRECT_OPERATIONS_NOT_SUPPORTED', @ERR_DIRECT_OPERATIONS_NOT_SUPPORTED);
	TranslationRegistry.Add('ERR_DOWNLOAD', @ERR_DOWNLOAD);
	TranslationRegistry.Add('ERR_DOWNLOAD_FILE_ASK', @ERR_DOWNLOAD_FILE_ASK);
	TranslationRegistry.Add('ERR_ENCRYPT_FAILED', @ERR_ENCRYPT_FAILED);
	TranslationRegistry.Add('ERR_FILE_NOT_EXISTS', @ERR_FILE_NOT_EXISTS);
	TranslationRegistry.Add('ERR_FILE_OPEN', @ERR_FILE_OPEN);
	TranslationRegistry.Add('ERR_GET_PUBLIC_SHARE', @ERR_GET_PUBLIC_SHARE);
	TranslationRegistry.Add('ERR_GET_TEMP_PUBLIC_LINK', @ERR_GET_TEMP_PUBLIC_LINK);
	TranslationRegistry.Add('ERR_GET_USER_SPACE', @ERR_GET_USER_SPACE);
	TranslationRegistry.Add('ERR_HTTP_GENERAL', @ERR_HTTP_GENERAL);
	TranslationRegistry.Add('ERR_INI_GENERAL', @ERR_INI_GENERAL);
	TranslationRegistry.Add('ERR_INSUFFICIENT_STORAGE', @ERR_INSUFFICIENT_STORAGE);
	TranslationRegistry.Add('ERR_INVALID_IDENTIFIER_NAME', @ERR_INVALID_IDENTIFIER_NAME);
	TranslationRegistry.Add('ERR_INVALID_SECTION_NAME', @ERR_INVALID_SECTION_NAME);
	TranslationRegistry.Add('ERR_INVITE_MSG', @ERR_INVITE_MSG);
	TranslationRegistry.Add('ERR_JSON_PARSING', @ERR_JSON_PARSING);
	TranslationRegistry.Add('ERR_LINE_HASH', @ERR_LINE_HASH);
	TranslationRegistry.Add('ERR_LIST_INVITES_MSG', @ERR_LIST_INVITES_MSG);
	TranslationRegistry.Add('ERR_LOAD_CAPTCHA', @ERR_LOAD_CAPTCHA);
	TranslationRegistry.Add('ERR_NAME_TOO_LONG', @ERR_NAME_TOO_LONG);
	TranslationRegistry.Add('ERR_NO_MASTER_PASSWORD', @ERR_NO_MASTER_PASSWORD);
	TranslationRegistry.Add('ERR_NO_PASSWORDS_STORED', @ERR_NO_PASSWORDS_STORED);
	TranslationRegistry.Add('ERR_OPERATION', @ERR_OPERATION);
	TranslationRegistry.Add('ERR_OTHER_GENERAL', @ERR_OTHER_GENERAL);
	TranslationRegistry.Add('ERR_PARSING_ANSWER', @ERR_PARSING_ANSWER);
	TranslationRegistry.Add('ERR_PARTIAL_UPLOAD_ABORT', @ERR_PARTIAL_UPLOAD_ABORT);
	TranslationRegistry.Add('ERR_PARTIAL_UPLOAD_ASK', @ERR_PARTIAL_UPLOAD_ASK);
	TranslationRegistry.Add('ERR_PARTIAL_UPLOAD_IGNORE', @ERR_PARTIAL_UPLOAD_IGNORE);
	TranslationRegistry.Add('ERR_PARTIAL_UPLOAD_RETRY', @ERR_PARTIAL_UPLOAD_RETRY);
	TranslationRegistry.Add('ERR_PARTIAL_UPLOAD_RETRY_EXCEED', @ERR_PARTIAL_UPLOAD_RETRY_EXCEED);
	TranslationRegistry.Add('ERR_PASSWORD_MATCH', @ERR_PASSWORD_MATCH);
	TranslationRegistry.Add('ERR_PUBLISH_FILE', @ERR_PUBLISH_FILE);
	TranslationRegistry.Add('ERR_PUBLISH_FILE_ASK', @ERR_PUBLISH_FILE_ASK);
	TranslationRegistry.Add('ERR_PUBLISH_MSG', @ERR_PUBLISH_MSG);
	TranslationRegistry.Add('ERR_READ_BYTES_FROM', @ERR_READ_BYTES_FROM);
	TranslationRegistry.Add('ERR_REGISTRATION', @ERR_REGISTRATION);
	TranslationRegistry.Add('ERR_SHARE_FOLDER_MSG', @ERR_SHARE_FOLDER_MSG);
	TranslationRegistry.Add('ERR_SOCKET_GENERAL', @ERR_SOCKET_GENERAL);
	TranslationRegistry.Add('ERR_TOKEN_UPDATE', @ERR_TOKEN_UPDATE);
	TranslationRegistry.Add('ERR_UNPUBLISH_FILE', @ERR_UNPUBLISH_FILE);
	TranslationRegistry.Add('ERR_UNPUBLISH_MSG', @ERR_UNPUBLISH_MSG);
	TranslationRegistry.Add('ERR_UNSHARE_FOLDER_MSG', @ERR_UNSHARE_FOLDER_MSG);
	TranslationRegistry.Add('ERR_UPLOAD', @ERR_UPLOAD);
	TranslationRegistry.Add('ERR_UPLOAD_FILE_ASK', @ERR_UPLOAD_FILE_ASK);
	TranslationRegistry.Add('ERR_UPLOAD_INFO', @ERR_UPLOAD_INFO);
	TranslationRegistry.Add('ERR_WHERE_IS_THE_FILE', @ERR_WHERE_IS_THE_FILE);
	TranslationRegistry.Add('ERR_WRITE_FAILED', @ERR_WRITE_FAILED);
	TranslationRegistry.Add('ERR_WRITE_NO_MASTER_PASSWORD', @ERR_WRITE_NO_MASTER_PASSWORD);
	TranslationRegistry.Add('ERR_WRONG_ENCRYPT_PASSWORD', @ERR_WRONG_ENCRYPT_PASSWORD);
	TranslationRegistry.Add('ERR_WRONG_FORMAT', @ERR_WRONG_FORMAT);
	TranslationRegistry.Add('ERR_WRONG_HASH_LENGTH', @ERR_WRONG_HASH_LENGTH);
	TranslationRegistry.Add('ERR_WRONG_SIZE_FORMAT', @ERR_WRONG_SIZE_FORMAT);
	TranslationRegistry.Add('HTTP_REQUEST', @HTTP_REQUEST);
	TranslationRegistry.Add('HTTP_REQUEST_BODY', @HTTP_REQUEST_BODY);
	TranslationRegistry.Add('HTTP_RESPONSE', @HTTP_RESPONSE);
	TranslationRegistry.Add('HTTP_RESPONSE_BODY', @HTTP_RESPONSE_BODY);
	TranslationRegistry.Add('HTTP_REDIRECT', @HTTP_REDIRECT);
	TranslationRegistry.Add('FILE_EXISTS_IGNORE', @FILE_EXISTS_IGNORE);
	TranslationRegistry.Add('FILE_EXISTS_OVERWRITE', @FILE_EXISTS_OVERWRITE);
	TranslationRegistry.Add('FILE_FOUND_BY_HASH', @FILE_FOUND_BY_HASH);
	TranslationRegistry.Add('INCOMING_LINKS_LISTING', @INCOMING_LINKS_LISTING);
	TranslationRegistry.Add('INVITE_FORM_TITLE', @INVITE_FORM_TITLE);
	TranslationRegistry.Add('LOGIN_IN_PROGRESS', @LOGIN_IN_PROGRESS);
	TranslationRegistry.Add('LOGIN_TO', @LOGIN_TO);
	TranslationRegistry.Add('METHOD_STR_HEAD', @METHOD_STR_HEAD);
	TranslationRegistry.Add('METHOD_STR_OPTIONS', @METHOD_STR_OPTIONS);
	TranslationRegistry.Add('METHOD_STR_POST', @METHOD_STR_POST);
	TranslationRegistry.Add('METHOD_STR_RECEIVE', @METHOD_STR_RECEIVE);
	TranslationRegistry.Add('MOUNTED_AS', @MOUNTED_AS);
	TranslationRegistry.Add('MULTIPLE_ITEMS', @MULTIPLE_ITEMS);
	TranslationRegistry.Add('MULTIPLE_ITEMS_DELETED', @MULTIPLE_ITEMS_DELETED);
	TranslationRegistry.Add('OK', @OK);
	TranslationRegistry.Add('PARTIAL_UPLOAD_ABORTED', @PARTIAL_UPLOAD_ABORTED);
	TranslationRegistry.Add('PARTIAL_UPLOAD_INFO', @PARTIAL_UPLOAD_INFO);
	TranslationRegistry.Add('PASSWORD_SAVED', @PASSWORD_SAVED);
	TranslationRegistry.Add('PREFIX_ACCESS_CHANGE', @PREFIX_ACCESS_CHANGE);
	TranslationRegistry.Add('PREFIX_ASK_ENCRYPTION_PASSWORD', @PREFIX_ASK_ENCRYPTION_PASSWORD);
	TranslationRegistry.Add('PREFIX_ASK_NEW_PASSWORD', @PREFIX_ASK_NEW_PASSWORD);
	TranslationRegistry.Add('PREFIX_ASK_PASSWORD', @PREFIX_ASK_PASSWORD);
	TranslationRegistry.Add('PREFIX_ASK_PROXY_PASSWORD', @PREFIX_ASK_PROXY_PASSWORD);
	TranslationRegistry.Add('PREFIX_ERR_CLOUD_INIT', @PREFIX_ERR_CLOUD_INIT);
	TranslationRegistry.Add('PREFIX_ERR_DELETE_DIR', @PREFIX_ERR_DELETE_DIR);
	TranslationRegistry.Add('PREFIX_ERR_DELETE_FILE', @PREFIX_ERR_DELETE_FILE);
	TranslationRegistry.Add('PREFIX_ERR_DIR_LISTING', @PREFIX_ERR_DIR_LISTING);
	TranslationRegistry.Add('PREFIX_ERR_FILE_COPY', @PREFIX_ERR_FILE_COPY);
	TranslationRegistry.Add('PREFIX_ERR_FILE_MOVE', @PREFIX_ERR_FILE_MOVE);
	TranslationRegistry.Add('PREFIX_ERR_FILE_PUBLISH', @PREFIX_ERR_FILE_PUBLISH);
	TranslationRegistry.Add('PREFIX_ERR_FILE_RENAME', @PREFIX_ERR_FILE_RENAME);
	TranslationRegistry.Add('PREFIX_ERR_FILE_RESTORE', @PREFIX_ERR_FILE_RESTORE);
	TranslationRegistry.Add('PREFIX_ERR_FILE_STATUS', @PREFIX_ERR_FILE_STATUS);
	TranslationRegistry.Add('PREFIX_ERR_FILE_UPLOADING', @PREFIX_ERR_FILE_UPLOADING);
	TranslationRegistry.Add('PREFIX_ERR_FOLDER_MOUNT', @PREFIX_ERR_FOLDER_MOUNT);
	TranslationRegistry.Add('PREFIX_ERR_FOLDER_UNMOUNT', @PREFIX_ERR_FOLDER_UNMOUNT);
	TranslationRegistry.Add('PREFIX_ERR_GET_USER_SPACE', @PREFIX_ERR_GET_USER_SPACE);
	TranslationRegistry.Add('PREFIX_ERR_INCOMING_REQUESTS_LISTING', @PREFIX_ERR_INCOMING_REQUESTS_LISTING);
	TranslationRegistry.Add('PREFIX_ERR_INVITE', @PREFIX_ERR_INVITE);
	TranslationRegistry.Add('PREFIX_ERR_INVITES_LISTING', @PREFIX_ERR_INVITES_LISTING);
	TranslationRegistry.Add('PREFIX_ERR_INVITE_MEMBER', @PREFIX_ERR_INVITE_MEMBER);
	TranslationRegistry.Add('PREFIX_ERR_INVITE_REJECT', @PREFIX_ERR_INVITE_REJECT);
	TranslationRegistry.Add('PREFIX_ERR_OAUTH', @PREFIX_ERR_OAUTH);
	TranslationRegistry.Add('PREFIX_ERR_PASSWORD_MATCH', @PREFIX_ERR_PASSWORD_MATCH);
	TranslationRegistry.Add('PREFIX_ERR_PATH_NOT_EXISTS', @PREFIX_ERR_PATH_NOT_EXISTS);
	TranslationRegistry.Add('PREFIX_ERR_REMOVE_TEMP_PUBLIC_LINK', @PREFIX_ERR_REMOVE_TEMP_PUBLIC_LINK);
	TranslationRegistry.Add('PREFIX_ERR_SHARD_RECEIVE', @PREFIX_ERR_SHARD_RECEIVE);
	TranslationRegistry.Add('PREFIX_ERR_SHARED_LINKS_LISTING', @PREFIX_ERR_SHARED_LINKS_LISTING);
	TranslationRegistry.Add('PREFIX_ERR_SHARE_FOLDER', @PREFIX_ERR_SHARE_FOLDER);
	TranslationRegistry.Add('PREFIX_ERR_TRASH_CLEAN', @PREFIX_ERR_TRASH_CLEAN);
	TranslationRegistry.Add('PREFIX_ERR_TRASH_LISTING', @PREFIX_ERR_TRASH_LISTING);
	TranslationRegistry.Add('PREFIX_ERR_UNSHARE_FOLDER', @PREFIX_ERR_UNSHARE_FOLDER);
	TranslationRegistry.Add('PREFIX_REDIRECTION_LIMIT', @PREFIX_REDIRECTION_LIMIT);
	TranslationRegistry.Add('PREFIX_SCAN', @PREFIX_SCAN);
	TranslationRegistry.Add('PREFIX_SHARD_RECEIVED', @PREFIX_SHARD_RECEIVED);
	TranslationRegistry.Add('PREFIX_STATUS', @PREFIX_STATUS);
	TranslationRegistry.Add('PROCEED_IGNORE', @PROCEED_IGNORE);
	TranslationRegistry.Add('PROCEED_RETYPE', @PROCEED_RETYPE);
	TranslationRegistry.Add('PROCEED_UPDATE', @PROCEED_UPDATE);
	TranslationRegistry.Add('PUBLISH_FILE_RETRY', @PUBLISH_FILE_RETRY);
	TranslationRegistry.Add('REDIRECTION_LIMIT', @REDIRECTION_LIMIT);
	TranslationRegistry.Add('REQUESTING_OAUTH_TOKEN', @REQUESTING_OAUTH_TOKEN);
	TranslationRegistry.Add('SHARD_OVERRIDDEN', @SHARD_OVERRIDDEN);
	TranslationRegistry.Add('SHARED_LINKS_LISTING', @SHARED_LINKS_LISTING);
	TranslationRegistry.Add('SPLIT_LARGE_FILE', @SPLIT_LARGE_FILE);
	TranslationRegistry.Add('SPLIT_LARGE_FILE_IGNORE', @SPLIT_LARGE_FILE_IGNORE);
	TranslationRegistry.Add('SPLIT_PARTIAL_UPLOAD_TITLE', @SPLIT_PARTIAL_UPLOAD_TITLE);
	TranslationRegistry.Add('SPLIT_PARTIAL_UPLOAD_MSG', @SPLIT_PARTIAL_UPLOAD_MSG);
	TranslationRegistry.Add('SPLIT_NO_SPACE_MSG', @SPLIT_NO_SPACE_MSG);
	TranslationRegistry.Add('SESSION_EXPIRED', @SESSION_EXPIRED);
	TranslationRegistry.Add('SESSION_REAUTHENTICATED', @SESSION_REAUTHENTICATED);
	TranslationRegistry.Add('TOKEN_UPDATED', @TOKEN_UPDATED);
	TranslationRegistry.Add('TRASH_LISTING', @TRASH_LISTING);
	TranslationRegistry.Add('TRY_ANOTHER_SHARD', @TRY_ANOTHER_SHARD);
	TranslationRegistry.Add('UNDEFINED_DOWNLOAD_SHARD', @UNDEFINED_DOWNLOAD_SHARD);
	TranslationRegistry.Add('UNDEFINED_UPLOAD_SHARD', @UNDEFINED_UPLOAD_SHARD);
	TranslationRegistry.Add('UNKNOWN_ITEM', @UNKNOWN_ITEM);
	TranslationRegistry.Add('UNSET_ITEM', @UNSET_ITEM);
	TranslationRegistry.Add('UPLOAD_FILE_RETRY', @UPLOAD_FILE_RETRY);
	TranslationRegistry.Add('UPLOAD_URL_OVERRIDDEN', @UPLOAD_URL_OVERRIDDEN);
	TranslationRegistry.Add('URL_OPEN', @URL_OPEN);
	TranslationRegistry.Add('USER_SPACE_INFO', @USER_SPACE_INFO);
	TranslationRegistry.Add('VERB_SET', @VERB_SET);
	TranslationRegistry.Add('VERB_UPDATE', @VERB_UPDATE);
	TranslationRegistry.Add('WAIT', @WAIT);
	TranslationRegistry.Add('WARN_CIPHER_CHANGE', @WARN_CIPHER_CHANGE);
	TranslationRegistry.Add('PREFIX_WARN_CIPHER_CHANGE', @PREFIX_WARN_CIPHER_CHANGE);
	TranslationRegistry.Add('WARN_ACCOUNT_NAME_SKIPPED', @WARN_ACCOUNT_NAME_SKIPPED);
	TranslationRegistry.Add('WARN_PROXY_PASSWORD_IGNORED', @WARN_PROXY_PASSWORD_IGNORED);
	TranslationRegistry.Add('WARN_QUOTA_EXHAUSTED', @WARN_QUOTA_EXHAUSTED);
	TranslationRegistry.Add('WARN_DISPATCHER_UNEXPECTED_FORMAT', @WARN_DISPATCHER_UNEXPECTED_FORMAT);
	TranslationRegistry.Add('TRANSLATION_NAME', @TRANSLATION_NAME);
	TranslationRegistry.Add('DFM_FORM_TITLE', @DFM_FORM_TITLE);
	TranslationRegistry.Add('DFM_TAB_ACCOUNTS', @DFM_TAB_ACCOUNTS);
	TranslationRegistry.Add('DFM_TAB_GLOBAL_SETTINGS', @DFM_TAB_GLOBAL_SETTINGS);
	TranslationRegistry.Add('DFM_TAB_NETWORK_SETTINGS', @DFM_TAB_NETWORK_SETTINGS);
	TranslationRegistry.Add('DFM_TAB_FILE_COMMENTS', @DFM_TAB_FILE_COMMENTS);
	TranslationRegistry.Add('DFM_TAB_STREAMING', @DFM_TAB_STREAMING);
	TranslationRegistry.Add('DFM_TAB_TRANSLATION', @DFM_TAB_TRANSLATION);
	TranslationRegistry.Add('DFM_BTN_APPLY', @DFM_BTN_APPLY);
	TranslationRegistry.Add('DFM_BTN_NEW', @DFM_BTN_NEW);
	TranslationRegistry.Add('DFM_BTN_DELETE', @DFM_BTN_DELETE);
	TranslationRegistry.Add('DFM_BTN_SET_PASSWORD', @DFM_BTN_SET_PASSWORD);
	TranslationRegistry.Add('DFM_BTN_RESET_UA', @DFM_BTN_RESET_UA);
	TranslationRegistry.Add('DFM_LBL_ACCOUNT_NAME', @DFM_LBL_ACCOUNT_NAME);
	TranslationRegistry.Add('DFM_LBL_PUBLIC_URL', @DFM_LBL_PUBLIC_URL);
	TranslationRegistry.Add('DFM_LBL_EMAIL', @DFM_LBL_EMAIL);
	TranslationRegistry.Add('DFM_LBL_APP_PASSWORD', @DFM_LBL_APP_PASSWORD);
	TranslationRegistry.Add('DFM_LBL_ENCRYPT_FILES', @DFM_LBL_ENCRYPT_FILES);
	TranslationRegistry.Add('DFM_LBL_ENCRYPT_BACKEND', @DFM_LBL_ENCRYPT_BACKEND);
	TranslationRegistry.Add('DFM_LBL_BYTES', @DFM_LBL_BYTES);
	TranslationRegistry.Add('DFM_LBL_CHUNK_OVERWRITE', @DFM_LBL_CHUNK_OVERWRITE);
	TranslationRegistry.Add('DFM_LBL_DELETE_FAIL_UPLOAD', @DFM_LBL_DELETE_FAIL_UPLOAD);
	TranslationRegistry.Add('DFM_LBL_OVERWRITE_LOCAL', @DFM_LBL_OVERWRITE_LOCAL);
	TranslationRegistry.Add('DFM_LBL_ICONS_MODE', @DFM_LBL_ICONS_MODE);
	TranslationRegistry.Add('DFM_LBL_OPERATION_ERROR', @DFM_LBL_OPERATION_ERROR);
	TranslationRegistry.Add('DFM_LBL_RETRY_ATTEMPTS', @DFM_LBL_RETRY_ATTEMPTS);
	TranslationRegistry.Add('DFM_LBL_RETRY_WAIT', @DFM_LBL_RETRY_WAIT);
	TranslationRegistry.Add('DFM_LBL_MS', @DFM_LBL_MS);
	TranslationRegistry.Add('DFM_LBL_SHOW_ACCOUNTS', @DFM_LBL_SHOW_ACCOUNTS);
	TranslationRegistry.Add('DFM_LBL_COPY_BETWEEN', @DFM_LBL_COPY_BETWEEN);
	TranslationRegistry.Add('DFM_LBL_SOCKET_TIMEOUT', @DFM_LBL_SOCKET_TIMEOUT);
	TranslationRegistry.Add('DFM_LBL_PROXY_TYPE', @DFM_LBL_PROXY_TYPE);
	TranslationRegistry.Add('DFM_LBL_PROXY_PORT', @DFM_LBL_PROXY_PORT);
	TranslationRegistry.Add('DFM_LBL_PROXY_USER', @DFM_LBL_PROXY_USER);
	TranslationRegistry.Add('DFM_LBL_PROXY_PASSWORD', @DFM_LBL_PROXY_PASSWORD);
	TranslationRegistry.Add('DFM_LBL_PROXY_SERVER', @DFM_LBL_PROXY_SERVER);
	TranslationRegistry.Add('DFM_LBL_UPLOAD_BPS', @DFM_LBL_UPLOAD_BPS);
	TranslationRegistry.Add('DFM_LBL_DOWNLOAD_BPS', @DFM_LBL_DOWNLOAD_BPS);
	TranslationRegistry.Add('DFM_LBL_DESC_FILENAME', @DFM_LBL_DESC_FILENAME);
	TranslationRegistry.Add('DFM_LBL_FILE_EXT', @DFM_LBL_FILE_EXT);
	TranslationRegistry.Add('DFM_LBL_COMMAND', @DFM_LBL_COMMAND);
	TranslationRegistry.Add('DFM_LBL_PARAMETERS', @DFM_LBL_PARAMETERS);
	TranslationRegistry.Add('DFM_LBL_START_PATH', @DFM_LBL_START_PATH);
	TranslationRegistry.Add('DFM_LBL_STREAMING_TYPE', @DFM_LBL_STREAMING_TYPE);
	TranslationRegistry.Add('DFM_LBL_LANGUAGE', @DFM_LBL_LANGUAGE);
	TranslationRegistry.Add('DFM_COL_ACCOUNT', @DFM_COL_ACCOUNT);
	TranslationRegistry.Add('DFM_COL_TYPE', @DFM_COL_TYPE);
	TranslationRegistry.Add('DFM_COL_EXTENSION', @DFM_COL_EXTENSION);
	TranslationRegistry.Add('DFM_GB_ACCOUNT_TYPE', @DFM_GB_ACCOUNT_TYPE);
	TranslationRegistry.Add('DFM_GB_FILE_SIZE', @DFM_GB_FILE_SIZE);
	TranslationRegistry.Add('DFM_GB_ENCRYPTION', @DFM_GB_ENCRYPTION);
	TranslationRegistry.Add('DFM_GB_PROXY', @DFM_GB_PROXY);
	TranslationRegistry.Add('DFM_GB_SPEED_LIMITS', @DFM_GB_SPEED_LIMITS);
	TranslationRegistry.Add('DFM_RB_PRIVATE', @DFM_RB_PRIVATE);
	TranslationRegistry.Add('DFM_RB_PUBLIC', @DFM_RB_PUBLIC);
	TranslationRegistry.Add('DFM_CB_TC_PASSWORD', @DFM_CB_TC_PASSWORD);
	TranslationRegistry.Add('DFM_CB_UNLIMITED_SIZE', @DFM_CB_UNLIMITED_SIZE);
	TranslationRegistry.Add('DFM_CB_SPLIT_FILES', @DFM_CB_SPLIT_FILES);
	TranslationRegistry.Add('DFM_CB_PRESERVE_TIME', @DFM_CB_PRESERVE_TIME);
	TranslationRegistry.Add('DFM_CB_LOAD_SSL', @DFM_CB_LOAD_SSL);
	TranslationRegistry.Add('DFM_CB_LOG_SPACE', @DFM_CB_LOG_SPACE);
	TranslationRegistry.Add('DFM_CB_OVERRIDE_SPLIT', @DFM_CB_OVERRIDE_SPLIT);
	TranslationRegistry.Add('DFM_CB_DISABLE_MT', @DFM_CB_DISABLE_MT);
	TranslationRegistry.Add('DFM_CB_URL_ENCODE', @DFM_CB_URL_ENCODE);
	TranslationRegistry.Add('DFM_CB_AUTO_UPDATE', @DFM_CB_AUTO_UPDATE);
	TranslationRegistry.Add('DFM_CB_TRASH', @DFM_CB_TRASH);
	TranslationRegistry.Add('DFM_CB_SHARED', @DFM_CB_SHARED);
	TranslationRegistry.Add('DFM_CB_INVITES', @DFM_CB_INVITES);
	TranslationRegistry.Add('DFM_CB_PRECALC_HASH', @DFM_CB_PRECALC_HASH);
	TranslationRegistry.Add('DFM_CB_CHECK_CRC', @DFM_CB_CHECK_CRC);
	TranslationRegistry.Add('DFM_CB_PROXY_TC_PASSWORD', @DFM_CB_PROXY_TC_PASSWORD);
	TranslationRegistry.Add('DFM_CB_CHANGE_UA', @DFM_CB_CHANGE_UA);
	TranslationRegistry.Add('DFM_CB_DESC_ENABLED', @DFM_CB_DESC_ENABLED);
	TranslationRegistry.Add('DFM_CB_DESC_EDITOR', @DFM_CB_DESC_EDITOR);
	TranslationRegistry.Add('DFM_CB_DESC_COPY_TO', @DFM_CB_DESC_COPY_TO);
	TranslationRegistry.Add('DFM_CB_DESC_COPY_FROM', @DFM_CB_DESC_COPY_FROM);
	TranslationRegistry.Add('DFM_CB_DESC_TRACK', @DFM_CB_DESC_TRACK);
	TranslationRegistry.Add('DFM_OPT_ASK_USER', @DFM_OPT_ASK_USER);
	TranslationRegistry.Add('DFM_OPT_IGNORE_FILE', @DFM_OPT_IGNORE_FILE);
	TranslationRegistry.Add('DFM_OPT_ABORT_OPERATION', @DFM_OPT_ABORT_OPERATION);
	TranslationRegistry.Add('DFM_OPT_SILENTLY_OVERWRITE', @DFM_OPT_SILENTLY_OVERWRITE);
	TranslationRegistry.Add('DFM_OPT_IGNORE', @DFM_OPT_IGNORE);
	TranslationRegistry.Add('DFM_OPT_RETRY', @DFM_OPT_RETRY);
	TranslationRegistry.Add('DFM_OPT_UNSET_RO_IGNORE', @DFM_OPT_UNSET_RO_IGNORE);
	TranslationRegistry.Add('DFM_OPT_UNSET_RO_ABORT', @DFM_OPT_UNSET_RO_ABORT);
	TranslationRegistry.Add('DFM_OPT_ENCRYPT_NO', @DFM_OPT_ENCRYPT_NO);
	TranslationRegistry.Add('DFM_OPT_ENCRYPT_ALWAYS', @DFM_OPT_ENCRYPT_ALWAYS);
	TranslationRegistry.Add('DFM_OPT_ENCRYPT_ASK_ONCE', @DFM_OPT_ENCRYPT_ASK_ONCE);
	TranslationRegistry.Add('DFM_OPT_ICONS_DEFAULT', @DFM_OPT_ICONS_DEFAULT);
	TranslationRegistry.Add('DFM_OPT_ICONS_INTERNAL', @DFM_OPT_ICONS_INTERNAL);
	TranslationRegistry.Add('DFM_OPT_ICONS_INTERNAL_OVERLAY', @DFM_OPT_ICONS_INTERNAL_OVERLAY);
	TranslationRegistry.Add('DFM_OPT_ICONS_EXTERNAL', @DFM_OPT_ICONS_EXTERNAL);
	TranslationRegistry.Add('DFM_OPT_ICONS_EXTERNAL_OVERLAY', @DFM_OPT_ICONS_EXTERNAL_OVERLAY);
	TranslationRegistry.Add('DFM_OPT_COPY_DISABLED', @DFM_OPT_COPY_DISABLED);
	TranslationRegistry.Add('DFM_OPT_COPY_VIA_HASH', @DFM_OPT_COPY_VIA_HASH);
	TranslationRegistry.Add('DFM_OPT_COPY_VIA_LINK', @DFM_OPT_COPY_VIA_LINK);
	TranslationRegistry.Add('DFM_OPT_HASH_AUTO', @DFM_OPT_HASH_AUTO);
	TranslationRegistry.Add('DFM_OPT_HASH_DELPHI', @DFM_OPT_HASH_DELPHI);
	TranslationRegistry.Add('DFM_OPT_HASH_BCRYPT', @DFM_OPT_HASH_BCRYPT);
	TranslationRegistry.Add('DFM_OPT_HASH_OPENSSL', @DFM_OPT_HASH_OPENSSL);
	TranslationRegistry.Add('DFM_OPT_NO_PROXY', @DFM_OPT_NO_PROXY);
	TranslationRegistry.Add('DFM_OPT_SOCKS5', @DFM_OPT_SOCKS5);
	TranslationRegistry.Add('DFM_OPT_SOCKS4', @DFM_OPT_SOCKS4);
	TranslationRegistry.Add('DFM_OPT_HTTP', @DFM_OPT_HTTP);
	TranslationRegistry.Add('DFM_OPT_STREAM_NONE', @DFM_OPT_STREAM_NONE);
	TranslationRegistry.Add('DFM_OPT_STREAM_DISABLED', @DFM_OPT_STREAM_DISABLED);
	TranslationRegistry.Add('DFM_OPT_STREAM_M3U8', @DFM_OPT_STREAM_M3U8);
	TranslationRegistry.Add('DFM_OPT_STREAM_DEFAULT', @DFM_OPT_STREAM_DEFAULT);
	TranslationRegistry.Add('DFM_OPT_STREAM_WEB', @DFM_OPT_STREAM_WEB);
	TranslationRegistry.Add('DFM_LV_ENCRYPT_ALWAYS', @DFM_LV_ENCRYPT_ALWAYS);
	TranslationRegistry.Add('DFM_LV_ENCRYPT_ASK', @DFM_LV_ENCRYPT_ASK);
	TranslationRegistry.Add('DFM_LV_ENCRYPT_NO', @DFM_LV_ENCRYPT_NO);
	TranslationRegistry.Add('DFM_LV_STREAM_NONE', @DFM_LV_STREAM_NONE);
	TranslationRegistry.Add('DFM_LV_STREAM_OFF', @DFM_LV_STREAM_OFF);
	TranslationRegistry.Add('DFM_LV_STREAM_M3U8', @DFM_LV_STREAM_M3U8);
	TranslationRegistry.Add('DFM_LV_STREAM_LINK', @DFM_LV_STREAM_LINK);
	TranslationRegistry.Add('DFM_LV_STREAM_WEB', @DFM_LV_STREAM_WEB);
	TranslationRegistry.Add('DFM_ASK_FORM_TITLE', @DFM_ASK_FORM_TITLE);
	TranslationRegistry.Add('DFM_ASK_LBL_PASSWORD', @DFM_ASK_LBL_PASSWORD);
	TranslationRegistry.Add('DFM_ASK_BTN_OK', @DFM_ASK_BTN_OK);
	TranslationRegistry.Add('DFM_ASK_CB_STORE_PWD', @DFM_ASK_CB_STORE_PWD);
	TranslationRegistry.Add('DFM_DEL_LBL_NAME', @DFM_DEL_LBL_NAME);
	TranslationRegistry.Add('DFM_DEL_LBL_FROM', @DFM_DEL_LBL_FROM);
	TranslationRegistry.Add('DFM_DEL_LBL_AT', @DFM_DEL_LBL_AT);
	TranslationRegistry.Add('DFM_DEL_LBL_BY', @DFM_DEL_LBL_BY);
	TranslationRegistry.Add('DFM_DEL_LBL_SIZE', @DFM_DEL_LBL_SIZE);
	TranslationRegistry.Add('DFM_DEL_BTN_RESTORE', @DFM_DEL_BTN_RESTORE);
	TranslationRegistry.Add('DFM_DEL_BTN_CANCEL', @DFM_DEL_BTN_CANCEL);
	TranslationRegistry.Add('DFM_DEL_BTN_RESTORE_ALL', @DFM_DEL_BTN_RESTORE_ALL);
	TranslationRegistry.Add('DFM_DEL_BTN_CLEAR_TRASH', @DFM_DEL_BTN_CLEAR_TRASH);
	TranslationRegistry.Add('DFM_INV_LBL_NAME', @DFM_INV_LBL_NAME);
	TranslationRegistry.Add('DFM_INV_LBL_OWNER_EMAIL', @DFM_INV_LBL_OWNER_EMAIL);
	TranslationRegistry.Add('DFM_INV_LBL_OWNER_NAME', @DFM_INV_LBL_OWNER_NAME);
	TranslationRegistry.Add('DFM_INV_LBL_ACCESS', @DFM_INV_LBL_ACCESS);
	TranslationRegistry.Add('DFM_INV_LBL_SIZE', @DFM_INV_LBL_SIZE);
	TranslationRegistry.Add('DFM_INV_LBL_INVITE_TOKEN', @DFM_INV_LBL_INVITE_TOKEN);
	TranslationRegistry.Add('DFM_INV_BTN_MOUNT', @DFM_INV_BTN_MOUNT);
	TranslationRegistry.Add('DFM_INV_BTN_CANCEL', @DFM_INV_BTN_CANCEL);
	TranslationRegistry.Add('DFM_INV_BTN_REJECT', @DFM_INV_BTN_REJECT);
	TranslationRegistry.Add('DFM_INV_BTN_UNMOUNT_COPY', @DFM_INV_BTN_UNMOUNT_COPY);
	TranslationRegistry.Add('DFM_INV_BTN_UNMOUNT_DELETE', @DFM_INV_BTN_UNMOUNT_DELETE);
	TranslationRegistry.Add('DFM_REM_LBL_PUBLIC_LINK', @DFM_REM_LBL_PUBLIC_LINK);
	TranslationRegistry.Add('DFM_REM_CB_PUBLIC_ACCESS', @DFM_REM_CB_PUBLIC_ACCESS);
	TranslationRegistry.Add('DFM_REM_BTN_OK', @DFM_REM_BTN_OK);
	TranslationRegistry.Add('DFM_REM_TAB_FOLDER_ACCESS', @DFM_REM_TAB_FOLDER_ACCESS);
	TranslationRegistry.Add('DFM_REM_TAB_DOWNLOAD_LINKS', @DFM_REM_TAB_DOWNLOAD_LINKS);
	TranslationRegistry.Add('DFM_REM_TAB_HASHES_LIST', @DFM_REM_TAB_HASHES_LIST);
	TranslationRegistry.Add('DFM_REM_TAB_DESCRIPTION', @DFM_REM_TAB_DESCRIPTION);
	TranslationRegistry.Add('DFM_REM_LBL_NEW_MEMBER', @DFM_REM_LBL_NEW_MEMBER);
	TranslationRegistry.Add('DFM_REM_LBL_ACCESS', @DFM_REM_LBL_ACCESS);
	TranslationRegistry.Add('DFM_REM_BTN_ADD', @DFM_REM_BTN_ADD);
	TranslationRegistry.Add('DFM_REM_BTN_SAVE_AS', @DFM_REM_BTN_SAVE_AS);
	TranslationRegistry.Add('DFM_REM_BTN_WRAP', @DFM_REM_BTN_WRAP);
	TranslationRegistry.Add('DFM_REM_BTN_CANCEL_SCAN', @DFM_REM_BTN_CANCEL_SCAN);
	TranslationRegistry.Add('DFM_REM_BTN_RESCAN', @DFM_REM_BTN_RESCAN);
	TranslationRegistry.Add('DFM_REM_BTN_LOAD_FILE', @DFM_REM_BTN_LOAD_FILE);
	TranslationRegistry.Add('DFM_REM_BTN_APPLY_HASHES', @DFM_REM_BTN_APPLY_HASHES);
	TranslationRegistry.Add('DFM_REM_BTN_F2_OK', @DFM_REM_BTN_F2_OK);
	TranslationRegistry.Add('DFM_REM_MI_CHANGE_ACCESS', @DFM_REM_MI_CHANGE_ACCESS);
	TranslationRegistry.Add('DFM_REM_MI_DROP_ACCESS', @DFM_REM_MI_DROP_ACCESS);
	TranslationRegistry.Add('DFM_REM_MI_REFRESH', @DFM_REM_MI_REFRESH);
	TranslationRegistry.Add('DFM_REM_OPT_READ_WRITE', @DFM_REM_OPT_READ_WRITE);
	TranslationRegistry.Add('DFM_REM_OPT_READ_ONLY', @DFM_REM_OPT_READ_ONLY);

	TranslationRegistry.Add('DFM_TRANS_DEFAULT', @DFM_TRANS_DEFAULT);
	TranslationRegistry.Add('DFM_TRANS_RESTORED', @DFM_TRANS_RESTORED);
	TranslationRegistry.Add('DFM_TRANS_APPLIED', @DFM_TRANS_APPLIED);
	TranslationRegistry.Add('DFM_TRANS_ERROR', @DFM_TRANS_ERROR);

	TranslationRegistry.Add('CONTENT_FIELD_DISABLED', @CONTENT_FIELD_DISABLED);
end;

initialization
	InitializeDefaults;
	BuildTranslationRegistry;

finalization
	FreeAndNil(TranslationRegistry);

end.
